spring:
  application:
    name: address-service
  datasource:
    url: jdbc:mysql://localhost:3306/spring
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 9090