spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: counterService
          uri: lb://COUNTER-SERVICE
          predicates:
            - Path=/counter/**

#    cloud:
#      gateway:
#        routes:
#          - id: counter-service
#            uri: lb://COUNTER-SERVICE
#            predicates:
#              - Path =/counter/**

#server:
#  port:8080

server:
  port: 8080

eureka:
    client:
      service-url:
        defaultZone: http://localhost:8083/eureka

